### ISSUE TITLE
Osa 6 Tiedostojen lukeminen, kirjoitusvirhe

### ISSUE THREAD

**Issue by Kalmazaton** [rage/ohjelmointi-24#8]
Osa 6, Tiedostojen lukeminen 
"Eri tiedostoissa olevien tietojen yhdistely" alaotsikon alla tekstissä kirjotusvirhe:
"Ohjelma käyttää aputietorakenteena kahta saankirjaa nimet ja palkat, joissa molemmissa avaimena toimii henkilötunnus:"
sanakirjaa on typotettu "saankirjaa"

**Comment by Gudkat** [comment]
korjattu. kiitos palautteesta.
